
  <section class="page-section mt-5" id="team">
  <div class="container">
  <h2 class="mb-5">Techo Wing</h2>
    As the present day generation has entered into a global village, there has been immense breakthrough in science and technology. But yet in this technocrat generation, there has been a great divide; a divide that has scaled one into space exploration, a 5D generation and has left the other devoid of basic amenities.<br /><br />

  India may be a bit better off in this aspect with the introduction of basic free internet services yet the digital divide is very prominent. India at present has the cheapest internet services in the world but majority of it has been used only for entertainment and not for learning.<br /><br />

  So, here is a need that in this platform of INDRA Trust, we are able to reach out people and reach them with technology. Though India is not at par in these parameters, we here thrive to provide people the basic knowledge about these. Before treating any basic ailments, we need to know its symptoms and syndromes INDRA trust is a platform where all the symptoms and syndromes of basic ailments can be found. But yet before this, there a e-medical services people need to thrive for, Basic sanitation can reduce many epidemics in the country.Drinking boiled or simple chlorinated water can solve the issue of many water borne diseases.<br /><br />

  India is a country of 1.3 billion people and the resources in the country to meet all the people is running out thick and fast. India being a tropical country is well endowed with sunshine 68% of the year. So, solar energy is an alternative. Though silicon technology is growing fast to tap solar power yet it’s quite costly. So we need to move to devices with better longevity and higher economic feasibility. Wind energy and thermal power other options of research in the country. India being a peninsula is Rich in marine resources. This not only gives option for tidal power but also provides a remedy to water crisis via desalination.<br /><br />

  India has imported technological know how from Israel to desalinize water at a cheap rate. Our ground water levels are depleting thick and fast and it’s high time people do their bits to save water. Desalination and reverse osmosis are going to play a huge role to overcome water crisis in states of Tamil Nadu, Karnataka , Gujarat and Rajasthan. Climate change and global warming is yet another obstacle to India’s growth. In the last few years India has been married with several severe cyclone, floods, avalanches, mud flow, cloud burst and landslides all due to global warming and climate change. It’s time we switch to greener options yet keeping in mind the 3R policy of reduce, reuse and recycle. We need to shift to organic farming to keep away the effects of bio-accumulation. Nature has a great capacity to cleanse itself. Rivers, lakes and oceans can clean itself with time. Sequestration of Carbon dioxide by oceans have been reduced due to frequent oil spills. Biological oxygen demand of Rivers have been increasing day by day. So, the only means to prevent it is the proper treatment of sewage and planting trees in heaps. While the other things require technical know-how, planting trees is what we can do in hindsight.<br /><br />

  Over the past few decades, India has become the IT hub of Asia and also the world. India is moving fast towards an attractive trade center of the world. India economy is slowly shifting from a agrarian one to the service economy. However, the sorry affair is that this is limited to only certain silicon cities if India and other state capitals while majority of districts are far away from this. So, in next few years India must thrive to bring in service sector to at least 30% districts of each state so that the digital divide is broken. Artificial intelligence in an exciting sector of advancement yet it’s introduction in India may hamper the labor based economy of the country.<br /><br />

  Things can be so many and so forth, yet it is applauble only if it reaches everyone and the government body monitoring it is transperant. So as a citizen, our efforts has to be to bring awareness at the grass root level. Only, then we can thrive towards excellence.<br /><br />

  </div>
  </section>
